apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: php
  name: php
  namespace: development
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php
    spec:
      containers:
      - image: ttregistry.azurecr.us/linux/php:49
        name: php
        ports:
        - containerPort: 83
        resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: php
  name: php
  namespace: development
spec:
  ports:
  - name: "port"
    port: 80
    targetPort: 83
  selector:
    app: php
status:
  loadBalancer: {}
