apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: ttregistry.azurecr.us/linux/php:53
        name: web
        ports:
        - containerPort: 83
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: web
  name: web
spec:
  ports:
  - name: "ports"
    port: 80
    targetPort: 83
  selector:
    app: web
status:
  loadBalancer: {}
