apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: linux-php
  name: linux-php
  namespace: development
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: linux-php
    spec:
      containers:
      - image: ttregistry.azurecr.us/linux/php:${BUILD_NUMBER}
        name: linux-php
        ports:
        - containerPort: 8080
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: linux-php
  name: linux-php
  namespace: development
spec:
  ports:
  - name: tcp-8080
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: linux-php
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
